### ISSUE TITLE
Instructor Feedback Week 5

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [laabsky/DonationTracker#3]
Good work on the one-to-many work!

- [ ] Time to implement the generic dao, which will allow you to get rid of your existing daos (update the tests to use the generic dao). This also means you'll likely be able to use that single dao for all of the data access in your project.
- [ ] Override the .equals method in each entity, so that your unit test assertions can take advantage of a very thorough entity comparison, rather than comparing field by field https://github.com/laabsky/DonationTracker/blob/48fcbe2d694051616064dd8d2786a47ca3ef2324/src/test/java/DonationTracker/persistence/ItemDaoTest.java#L120-L121

**Comment by laabsky** [comment]
The generic dao was on my TODO list, but as the weeks went on, I decided not to implement it since I already had daos for user and item, meaning I only had one more to make. It seemed like more work to implement the generic dao than just create the role dao. 

.equals implemented for insert and update.
