### ISSUE TITLE
Week 9 - Rest Service Feedback

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [laabsky/DonationTracker#6]
- [x] Review best practices for REST naming. https://github.com/laabsky/DonationTracker/blob/9137e4664d7f2e6f9c70401169895a534d3f233f/src/main/java/DonationTracker/controller/ServicesResponse.java#L14. The path here should be users - representing the resource you'll be returning.
- [ ] You could use a call to toString on each user in the list to return the users as strings. 
- [x] To convert a java object to JSON you could write that manually or use one of several java libraries (a google search should yield several options including Jackson). 
- [ ] package naming - usually all lowercase. DonationTracker.persistence; versus  donationtracker.persistence;  "Package names are written in all lower case to avoid conflict with the names of classes or interfaces. "
- [x] Services class might be better placed in the controller package since it's more of a "router", it doesn't really do much work.
- [x] ServicesResponse might be better named UserService? It could live in a service package.

**Comment by laabsky** [comment]
Didn't change the response to toString because I had it working creating the json object from the existing list. Didn't change the package because at this point it would include changing so many imports that I don't want to risk breaking the app. I will definitely implement that on future projects. All other changes made.
